apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: false
        customQuery: true
        query: '{job="wordpress"} |~ "${__span.traceId}"'
      nodeGraph:
        enabled: true
      streamingEnabled:
        search: false
